In [3]:
import numpy as np

arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [28]:
#lst1 = []
#lst2 = []

lst1 = [int(item) for item in input("Enter the list items : ").split()] 
lst2 = [int(item) for item in input("Enter the list items : ").split()] 
      
print(lst1,"\n",lst2)

arr1 = np.array(lst1)
arr2 = np.array(lst2)
print(arr1, arr2)

arr = np.concatenate((arr1,arr2))
print(arr)



Enter the list items : 1 2 3 4 5
Enter the list items : 6 7 8 9 10
[1, 2, 3, 4, 5] 
 [6, 7, 8, 9, 10]
[1 2 3 4 5] [ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
a_1d = np.arange(3)
print(a_1d)

a_2d = np.arange(12).reshape((3, 4))
print(a_2d)

a_3d = np.arange(24).reshape((2, 3, 4))
print(a_3d)

#dimension
print(a_1d.ndim)
print(a_2d.ndim)
print(a_3d.ndim)

#size
print(a_1d.size)
print(a_2d.size)
print(a_3d.size)

[0 1 2]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
1
2
3
3
12
24


In [32]:
a_1d_array = np.array([1, 2, 3, 4])
print(a_1d_array)

reshaped_to_2d = np.reshape(a_1d_array, (-1, 2))
print(reshaped_to_2d)

[1 2 3 4]
[[1 2]
 [3 4]]


In [34]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

arr2 = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(arr2)

print("Vertical stacking:\n", np.vstack((arr1, arr2)))
print("\nHorizontal stacking:\n", np.hstack((arr1, arr2))) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
Vertical stacking:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]
 [44 55 66]
 [77 88 99]]

Horizontal stacking:
 [[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]


In [37]:
a_list = [1, 1, 2, 2, 3]
a_set = set(a_list)
number_of_unique_values = len(a_set)
print(number_of_unique_values)

3
